version: '3.5'
services:
  typoteka.task.postgres:
    image: postgres:14-alpine
    container_name: typoteka.task.postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: test
      POSTGRES_DB: typoteka-task
    ports:
      - 5432:5432
    volumes:
      - typoteka.postgres.task:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d test" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    networks:
      - typoteka.task

  typoteka.task.pgadmin:
    image: dpage/pgadmin4
    container_name: typoteka.task.pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "keks@htmlacademy.local"
      PGADMIN_DEFAULT_PASSWORD: "test"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - 8082:80
    networks:
      - typoteka.task

volumes:
  typoteka.postgres.task:

networks:
  typoteka.task:
      driver: bridge